import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  dashboard
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  dashboard: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Navbar />

        <main className='container'>
          <section className='py-6'>{children}</section>

          <section className='flex gap-6 '>
            {team}
            {dashboard}
          </section>
        </main>
      </body>
    </html>
  );
}
